import pandas as pd
import numpy as np
stock_data = pd.read_csv (r'C:\Users\user\Downloads\Risk and Returns_ The Sharpe Ratio\datasets\stock_data.csv',parse_dates=['Date'],index_col='Date')
benchmark_data=pd.read_csv(r'C:\Users\user\Downloads\Risk and Returns_ The Sharpe Ratio\datasets\benchmark_data.csv', parse_dates=['Date'],index_col='Date')
print(stock_data)
print(benchmark_data)
stock_data.dropna()
benchmark_data.dropna()
stock_data.info()
benchmark_data.info()
print(stock_data.head())
print(benchmark_data.head())
stock_data.plot(subplots=True, title='Stock Data')
stock_data.describe()
benchmark_data.plot(subplots=False, title='S&P 500')
benchmark_data.describe()
stock_data.pct_change()
stock_data.pct_change().plot(title='Stock Returns')
stock_data.pct_change().describe()
benchmark_data['S&P 500'].pct_change()
benchmark_data.pct_change().plot(title='Index Return')
benchmark_data['S&P 500'].pct_change().describe()
excess_returns=stock_data.pct_change().sub(benchmark_data['S&P 500'].pct_change(),axis=0)
excess_returns.describe()
excess_returns.plot(subplots=False,title='Excess Returns')
avg_excess_return=excess_returns.mean()
avg_excess_return.plot.bar(title='Mean of the Return Difference')
sd_excess_return=excess_returns.std()
sd_excess_return.plot.bar(title='Standard Deviation of the Return Difference')
daily_sharpe_ratio=avg_excess_return.div(sd_excess_return)
annual_factor=np.sqrt(252)
annual_sharpe_ratio=daily_sharpe_ratio.mul(annual_factor)
annual_sharpe_ratio.plot.bar(title='Annualized Sharpe Ratio: Stocks vs S&P 500')
buy_amazon=True,
buy_facebook=False
